version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsletter
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  newsletter-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsletter-service
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
