spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/newsletter?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create  # ?? validate, create, create-drop ?
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true