spring:
  application:
    name: newsletter-service

  datasource:
    url: jdbc:mysql://localhost:3306/newsletter?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kkd06155@gmail.com
    password: qpdthnfnitrptrks
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  thymeleaf:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

server:
  port: 8080

logging:
  level:
    org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessor: DEBUG
    com.sejong.newsletterservice.infrastructure.email: DEBUG